### ISSUE TITLE
Update (path to) imagenet labels in notebook attack_defense_imagenet

### ISSUE THREAD

**Issue by jinglin80** [IBM/adversarial-robustness-toolbox#109]
I try to run the notebook example: detector-for-CIFAR10. However, CIFAR10 cannot be loaded. 
Following is the code and the error: 
(x_train, y_train), (x_test, y_test), min_, max_ = load_dataset('cifar10')

class_descr = ['airplane', 'automobile', 'bird', 'cat', 'deer', 'dog', 'frog', 'horse', 'ship', 'truck']
---------------------------------------------------------------------------
UnpicklingError                           Traceback (most recent call last)
<ipython-input-2-530922867e55> in <module>
----> 1 (x_train, y_train), (x_test, y_test), min_, max_ = load_dataset('cifar10')
      2 
      3 class_descr = ['airplane', 'automobile', 'bird', 'cat', 'deer', 'dog', 'frog', 'horse', 'ship', 'truck']

~/anaconda3/lib/python3.6/site-packages/art/utils.py in load_dataset(name)
    566         return load_mnist()
    567     if "cifar10" in name:
--> 568         return load_cifar10()
    569     if "stl10" in name:
    570         return load_stl()

~/anaconda3/lib/python3.6/site-packages/art/utils.py in load_cifar10(raw)
    403     for i in range(1, 6):
    404         fpath = os.path.join(path, 'data_batch_' + str(i))
--> 405         data, labels = load_batch(fpath)
    406         x_train[(i - 1) * 10000: i * 10000, :, :, :] = data
    407         y_train[(i - 1) * 10000: i * 10000] = labels

~/anaconda3/lib/python3.6/site-packages/art/utils.py in load_batch(fpath)
    380                 content = cPickle.load(file_)
    381             else:
--> 382                 content = cPickle.load(file_, encoding='bytes')
    383                 content_decoded = {}
    384                 for key, value in content.items():

UnpicklingError: pickle data was truncated

**Comment by beat-buesser** [comment]
Hi @jinglin80 Thank you for raising this issue.

Please try running the notebook one the branch `dev`.

This issue is the same as #63. We have already fixed it on branch `dev` with #98. We will soon update branch `master`.

**Comment by jinglin80** [comment]
I run the notebook on the branch dev. However, I got the same error message. The CIFAR-10 dataset cannot be loaded properly.

UnpicklingError                           Traceback (most recent call last)
<ipython-input-2-f43aa2fb3c25> in <module>
----> 1 (x_train, y_train), (x_test, y_test), min_, max_ = load_dataset('cifar10')
      2 
      3 num_samples_train = 100
      4 num_samples_test = 100
      5 x_train = x_train[0:num_samples_train]

~/anaconda3/lib/python3.6/site-packages/art/utils.py in load_dataset(name)
    566         return load_mnist()
    567     if "cifar10" in name:
--> 568         return load_cifar10()
    569     if "stl10" in name:
    570         return load_stl()

~/anaconda3/lib/python3.6/site-packages/art/utils.py in load_cifar10(raw)
    403     for i in range(1, 6):
    404         fpath = os.path.join(path, 'data_batch_' + str(i))
--> 405         data, labels = load_batch(fpath)
    406         x_train[(i - 1) * 10000: i * 10000, :, :, :] = data
    407         y_train[(i - 1) * 10000: i * 10000] = labels

~/anaconda3/lib/python3.6/site-packages/art/utils.py in load_batch(fpath)
    380                 content = cPickle.load(file_)
    381             else:
--> 382                 content = cPickle.load(file_, encoding='bytes')
    383                 content_decoded = {}
    384                 for key, value in content.items():

UnpicklingError: pickle data was truncated

**Comment by beat-buesser** [comment]
I'm not able to reproduce your error message. The notebook runs fine on branch `dev`.

Please try cleaning your ART data directory ~/.art/data/. Maybe your previous download got corrupted.

**Comment by jinglin80** [comment]
Could it because I do not have torch == 0.4.0 as required in test_requirements.txt?

**Comment by beat-buesser** [comment]
I think the torch version should not be a problem here.

Which version of Python are you using?
Could you please show the output of `ls -lh ~/.art/data/`?

**Comment by jinglin80** [comment]
The problem solved!!! Thank you.

However, when I run the notebook attack_defense_imagenet, I got following
error:

[image: image.png]

**Comment by beat-buesser** [comment]
How did you solve it?

**Comment by beat-buesser** [comment]
I cannot see the image in you previous message. Could you please upload the image or its message again?

**Comment by jinglin80** [comment]
I delete the old version, reinstall dev version, and clear ~.art/data.

**Comment by jinglin80** [comment]
Here you goes.

The code (from attack_defense_imagenet notebook) I run:
from os.path import join, abspath, expanduser

# Get Imagenet labels
path = expanduser('~/git/nemesis')
with open(join(path, "imagenet/labels.txt"), "r") as f_input:
    class_names = eval(f_input.read())

# Get some data
image_file = join(path,'test_api/clean100/n04479046_2998_224x224.jpg')
image_ = image.load_img(image_file, target_size=(224, 224))
img = image.img_to_array(image_)
plt.imshow(img / 255)
img = img[None, ...]

# Predict for clean image
pred = classifier.predict(img)
label = np.argmax(pred, axis=1)[0]
confidence = pred[:,label][0]
print('Prediction:', class_names[label], '- confidence
{0:.2f}'.format(confidence))

The error message I got:
---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
<ipython-input-3-eca6ea55b7ba> in <module>
3 # Get Imagenet labels
4 path = expanduser('~/git/nemesis')
----> 5 with open(join(path, "imagenet/labels.txt"), "r") as f_input:
 6     class_names = eval(f_input.read())
7
FileNotFoundError: [Errno 2] No such file or directory:
'/Users/jinglin/git/nemesis/imagenet/labels.txt'

**Comment by beat-buesser** [comment]
Thank you! This is indeed an error. It looks like the file with the imagenet class names got lost.

I'll rename this issue accordingly and try to fix it soon.

**Comment by beat-buesser** [comment]
@jinglin80 I have fixed the notebook on branch `development_issue_109`. If you have time, please let me know if it works for you.
