### ISSUE TITLE
HopSkipJump is very slow when attacking pytorch models

### ISSUE THREAD

**Issue by GuanlinLee** [IBM/adversarial-robustness-toolbox#127]
I try to use HopSkipJump to attack a ResNet model based on PyTorch 1.0.
But I find that I spend about 6 hours waiting for the result, this attack didn't finish even one batch which I set 200 MNIST images in. BTW, I implied this attack on RTX Titan.
Is this normal? I try to use the default HopSkipJump config firstly and then I reduced the max_eval from 10k to 100, but it still worked slowly (one batch for hours). Which params should I change to get a fast one?

**Comment by mathsinn** [comment]
Hi @GuanlinLee 

Thank you for raising this issue. Did you have a look at this notebook: https://github.com/IBM/adversarial-robustness-toolbox/blob/master/notebooks/hopskipjump_attack.ipynb

It could give you some guidance on parameters that we found work well on ResNet.

**Comment by GuanlinLee** [comment]
@mathsinn Thanks a lot for this useful notebook. I try to set the params of the HopSkipJump as 'max_iter=0, max_eval=1000, init_eval=10' and find it does attack much faster than before. But I read the paper [https://arxiv.org/pdf/1904.02144.pdf](url). In the codes responding to this paper, they used params as 'max_iter=64, max_eval=10000, init_eval=100'. I want to know whether it is important to use a big value. And when I tried to use the params above, it spent hours attacking one batch as I said.

**Comment by mathsinn** [comment]
@GuanlinLee The more iterations you run, the smaller will be the norm of the perturbation. If you look at Figure 3 in that paper, you can see that with more than 2K queries (on MNIST), the norm only slightly decreases. Presumably in their code, the authors chose an extremely large number of iterations beyond which they didn't observe any practical decrease of the norm anymore.

I'm closing this issue as technically this isn't really an issue of the library, but please feel free to post any additional observations or findings in this thread.
