### ISSUE TITLE
Pytorch examples

### ISSUE THREAD

**Issue by ksivaman** [IBM/adversarial-robustness-toolbox#128]
**Description**

It is extremely difficult to start using the toolbox just by looking at the docs or the source code . The examples given in the *examples* folder seem to be extremely useful. However, all the files in the *examples* folder are using Keras or Tensorflow. Support for other popular frameworks such as Pytorch would be extremely useful.

**Comment by beat-buesser** [comment]
Hi @ksivaman , thank you very much for using ART and for your great suggestions! Indeed we'll try to provide additional examples including Pytorch  very soon to facilitate getting started with ART.

In case you have by now already a working Pytorch example created by yourself, we would be very happy to include it in ART?

Please feel free to also join our Slack channel following the instructions on README, there we will be able to answer more detailed question about how to use ART.

**Comment by mathsinn** [comment]
@ksivaman I'd suggest to take a look also at some of the unit tests, e.g. https://github.com/IBM/adversarial-robustness-toolbox/blob/master/tests/classifiers/test_pytorch.py

They give an idea how to wrap Pytorch models for usage in ART. Note that, once you've wrapped your models in an ART classifier, the application of attacks, defences etc. is the same regardless of the backend framework you're using.

But you're right, it'll be good to demonstrate this end-to-end with additional examples.

**Comment by ksivaman** [comment]
I have made a PR for a pytorch example @beat-buesser .

**Comment by beat-buesser** [comment]
@ksivaman That's great, thank you very much! Your contribution will be helpful to many Pytorch and ART users. I'll merge #129 as soon as possible.
