### ISSUE TITLE
need torch to use KerasClassifier

### ISSUE THREAD

**Issue by JeremBlain** [IBM/adversarial-robustness-toolbox#13]
Hello. I tried to use this toolbox to create some adversarial example.
When I write
`from art.classifiers import KerasClassifier`

It prints me an error :
` No module named 'torch'`

the example cifar_adversarial_training.py doesn't work either. (same error)
Edit : actually, none of the examples work.
Edit2 : even the run_tests script doesn't work (for the same reason)

Why do I need torch to use this toolbox with keras ?

**Comment by ririnicolae** [comment]
Hi! Thanks for reporting this issue! We're working on fixing it  and will let you know when it's done.
