### ISSUE TITLE
mnist_poison_detection.py example error

### ISSUE THREAD

**Issue by lea4n** [IBM/adversarial-robustness-toolbox#133]
**Describe the bug**
When run the "mnist_poison_detection.py", an error "TypeError: __init__() got multiple values for argument 'model'" occurs in line 69,     classifier = KerasClassifier((min_, max_), model=model).

**System information (please complete the following information):**
 - OS: Ubuntu 16.04.1 LTS and kernel is 4.4.0-57-generic
 - Python version: 3.7.3(Anaconda)
 - ART version or commit number: master
 - TensorFlow / Keras / PyTorch / MXNet version: Keras,2.2.4 and TensorFlow,1.14.0

**Comment by beat-buesser** [comment]
Hi @lea4n Thank you for bringing this to our attention and especially for already providing the solution with#135. We'll also check all the other examples and update them.

**Comment by beat-buesser** [comment]
Closed with #135
