### ISSUE TITLE
can't load imagenet dataset

### ISSUE THREAD

**Issue by JeremBlain** [IBM/adversarial-robustness-toolbox#14]
Hello, I am using the function load_dataset() but it doesn't work.

I have the following error : 
~\Anaconda3\lib\site-packages\art\utils.py in load_imagenet()
    313 
    314     dataset = np.asarray(dataset)
--> 315     y = to_categorical(np.asarray([label] * len(dataset)), 1000)
    316 
    317     try:

UnboundLocalError: local variable 'label' referenced before assignment

and in utils.py, int the function load_imagenet() : 
`fpath = get_file('imagenet_class_index.json', class_index_path, cache_subdir='models')
    class_index = json.load(open(fpath))

    for k, v in class_index.items():
        if v[0] == class_id:
            label = k
            break`

I can't find the file imagenet_class_index.json, so I can't check if it's there or if it's correct.
(I get the download)

**Comment by ririnicolae** [comment]
Thank you for reporting this problem! `load_imagenet` is a helper function that does *not* download the dataset. It thus fails when the data is not present and under the assumed format. Considering the size of ImageNet, it does not make sense to download it in a synchronous mode when using the library. This considered, the helper function has very little added value, and we will be removing it to avoid confusion.

You can still use the library with any of the other available datasets (MNIST, CIFAR10 and STL). Their respective sizes are small, and they will be downloaded by the helper function `load_dataset`.
