### ISSUE TITLE
feature_squeezing.py clip_values is wrong

### ISSUE THREAD

**Issue by duoergun0729** [IBM/adversarial-robustness-toolbox#16]
adversarial-robustness-toolbox/art/defences/feature_squeezing.py

        if clip_values[1] != 0:
            x_ = x_ / clip_values[1]

if clip_values[0] is not 0, this will be wrong , the right is 

        if clip_values[1] != 0:
            x_ = x_ / （clip_values[1]-clip_values[0]）

**Comment by ririnicolae** [comment]
Thanks for pointing this out, @duoergun0729! Fixing it now!
