### ISSUE TITLE
Should we use the preprocess for the image in notebooks/attack_defense_imagenet.ipynb ?

### ISSUE THREAD

**Issue by davidlee1999** [IBM/adversarial-robustness-toolbox#17]
I think that the variable "img" in the third block of code should add a step of preprocess:
`img = preprocess_input(img)` 
And then the reverse the preprocess for the generated adversarial example later.

Maybe other notebook example has the same problem, could you check it?

**Comment by ririnicolae** [comment]
Yes, you're right, I will add the preprocessing step. This is not an issue for the notebook on poisoning, as that example works on MNIST, which is preprocessed (normalized to 1) when loaded.
