### ISSUE TITLE
No consensus in reporting success rate of an attack

### ISSUE THREAD

**Issue by felentovic** [IBM/adversarial-robustness-toolbox#188]
Some of the attacks report their success rate as a percentage (scale 0-100) and some as a rate (scale 0-1).
e.g Carlini attack:
<pre>
logger.info('Success rate of C&W L_2 attack: %.2f%%',
                    100 * compute_success(self.classifier, x, y, x_adv, self.targeted, batch_size=self.batch_size))</pre>

Universal perturbation:
<pre>
fooling_rate = np.sum(pred_y_max != y_adv) / nb_instances <br/>
.... <br/>
logger.info('Success rate of universal perturbation attack: %.2f%%', fooling_rate)</pre>

**Comment by beat-buesser** [comment]
Hi @felentovic Thank you very much for using ART and informing us about your observation. You are right, all success rates should be reported as percentages. Would you be interested to fix this issue?

**Comment by felentovic** [comment]
Hey @beat-buesser thank you for your quick reply. I would like to help by fixing this issue :)

**Comment by beat-buesser** [comment]
That's great!
I'll assign the issue to you and please let me know anytime if you have any questions or need support.

**Comment by felentovic** [comment]
Hey it seems that the PoisoningAttackSVM, can be targeted also, but it doesn't accept the targeted flag in the constructor. Should I fix that?

**Comment by beat-buesser** [comment]
Would you proposal include implementing additional code for the targeted attack or just the flag in the constructor?
I think if we continue we should create a separate issue for this.
Let me check with @ebubae who implemented PoisoningAttackSVM. @ebubae what do you think about @felentovic's proposal above?

**Comment by ebubae** [comment]
Hey @felentovic

`PoisoningAttackSVM` currently only supports binary classifiers. Every attack is targeted to either an optional `y` value or to the opposite of the model's current classification of the point. Although an targeted flag could be useful for future support with multi-label classifiers, it may be more cumbersome that its worth at its current state.

**Comment by felentovic** [comment]
@ebubae I agree with your opinion. My idea was to add logging of success rate for classifiers who also don't do that currently(e.g `PoisoningAttackSVM`) and to do it using the `compute success` method from `utils`:
`compute_success(classifier, x_clean, labels, x_adv, targeted=False, batch_size=1)` 

Would this be the right way to use the mentioned method then?:
`targeted = y is not None`
`x_adv = np.array(all_poison).reshape((num_poison, num_features))`
`compute_success(self.classifier, x, y, x_adv, targeted=targeted, batch_size=self.batch_size)`

**Comment by ebubae** [comment]
Yes that would correct.

**Comment by beat-buesser** [comment]
Hi @felentovic Just checking, do you have everything you need to make good progress?
