### ISSUE TITLE
EOFError: Ran out of input

### ISSUE THREAD

**Issue by zhjikoshlizhzc** [IBM/adversarial-robustness-toolbox#194]
When I run python get_started_scikit_learn.py, A error occurred.
Traceback (most recent call last):
  File "C:\Users\acer\Anaconda3\envs\ART2\lib\site-packages\numpy\lib\npyio.py", line 447, in load
    return pickle.load(fid, **pickle_kwargs)
EOFError: Ran out of input

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "get_started_scikit_learn.py", line 16, in <module>
    (x_train, y_train), (x_test, y_test), min_pixel_value, max_pixel_value = load_mnist()
  File "C:\Users\acer\Anaconda3\envs\ART2\lib\site-packages\art\utils.py", line 484, in load_mnist
    dict_mnist = np.load(path)
  File "C:\Users\acer\Anaconda3\envs\ART2\lib\site-packages\numpy\lib\npyio.py", line 450, in load
    "Failed to interpret file %s as a pickle" % repr(file))
OSError: Failed to interpret file '/tmp\\.art\\mnist.npz' as a pickle

**Comment by beat-buesser** [comment]
Hi @zhjikoshlizhzc Thank you for using ART and raising this issue! We will investigate and fix it as soon as possible.

**Comment by ririnicolae** [comment]
Hey, @zhjikoshlizhzc! Could you please check and let us know if `/tmp/.art/mnist.npz` actually exists on your system and has size non-zero? Could you also post the content of `tmp/.art/config.json`?

This might all be a glitch of ART running on Windows. Let us know and I'll look into it.

**Comment by zhjikoshlizhzc** [comment]
/tmp/.art/mnist.npz does not exist actually.
And There is only one  line in tmp/.art/config.json:
{
    "DATA_PATH": "C:\\Users\\acer\\.art\\data"
}
Thanks a lot for replying my question!
