### ISSUE TITLE
Potential Bug in JSMA implementation

### ISSUE THREAD

**Issue by keykholt** [IBM/adversarial-robustness-toolbox#196]
When calling generate for a JSMA attack (saliency_map.py), after a single interation, the all_feat array is supposed to be updated for the two pixels that were chosen based on the map. Currently, it is implemented as:

```
# Update used features
 all_feat[active_indices][np.arange(len(active_indices)), feat_ind[:, 0]] = 1
all_feat[active_indices][np.arange(len(active_indices)), feat_ind[:, 1]] = 1
```

However, the actual array doesn't seem to be updated. I implemented the same function directly and found that printing all_feat seems to show the same before and after state of all 0's.

Furthermore, changing gamma from 1 to a very small number (such as 0.00000001) doesn't have an effect on the attack. It still runs until it finds a successful perturbation, thus ignoring gamma. This seems to be due to the fact that all_feat is always all 0's so the sum is never greater than gamma.

I'd expect that the attack would stop either when it finds a successful attack or if the # of modified pixels > gamma.

**Comment by beat-buesser** [comment]
Hi @keykholt, Thank you for using ART and raising this issue! Could you please provide information about the library versions you are using (ART, TensorFlow, Keras, etc.)? If possible could you show us a short script on how to reproduce this issue?

Would you be interested to investigate and implement a possible solution?

**Comment by keykholt** [comment]
Using ART version 1.0. Here is an example on MNIST for a single input.

```
import warnings
warnings.filterwarnings('ignore')
from keras.models import load_model
from art import DATA_PATH
from art.utils import load_dataset, get_file
from art.classifiers import KerasClassifier
import numpy as np

(x_train, y_train), (x_test, y_test), min_, max_ = load_dataset('mnist')
path = get_file('mnist_cnn_original.h5', extract=False, path=DATA_PATH,
                url='https://www.dropbox.com/s/p2nyzne9chcerid/mnist_cnn_original.h5?dl=1')
classifier_model = load_model(path)
classifier = KerasClassifier(clip_values=(min_, max_), model=classifier_model, use_logits=False)
from art.attacks import SaliencyMapMethod

#First we try with gamma=1, this means that the attack should run until it fools the classifier or uses all of the features
print("--------- Gamma = 1 ---------------")
print("Original Predicted Label:", np.argmax(classifier.predict(np.array([x_test[0]])),axis=1))
attack = SaliencyMapMethod(classifier=classifier, gamma=1)
x_adv = attack.generate(np.array([x_test[0]]), y=np.array([9]))
print("Adv Predicted Label:", np.argmax(classifier.predict(x_adv[:2]),axis=1))
print("Number of features changed", np.sum(np.array(x_adv[0],dtype=np.float32) != np.array(x_test[0],dtype=np.float32)))

#Now we set gamma to a very small value (close to 0). It should stop after the first iteration
print("--------- Gamma = 0.0000000000001 ---------------")
print("Original Predicted Label:", np.argmax(classifier.predict(np.array([x_test[0]])),axis=1))
attack = SaliencyMapMethod(classifier=classifier, gamma=.0000000000001)
x_adv = attack.generate(np.array([x_test[0]]), y=np.array([9]))
print("Adv Predicted Label:", np.argmax(classifier.predict(x_adv[:2]),axis=1))
print("Number of features changed", np.sum(np.array(x_adv[0],dtype=np.float32) != np.array(x_test[0],dtype=np.float32)))
```

Running the above code, I get the same number of features changed despite setting one of the gamma's close to 0. If I add `print("Selected Features:", feat_ind, "all_feat sum:", np.sum(all_feat))` to line 125 of saliency_map.py, I see that the sum is always 0.

What worked for me was to change  123-124 from:
```
all_feat[active_indices][np.arange(len(active_indices)), feat_ind[:, 0]] = 1
all_feat[active_indices][np.arange(len(active_indices)), feat_ind[:, 1]] = 1
```
to 
```
all_feat[active_indices, feat_ind[:, 0]] = 1
all_feat[active_indices, feat_ind[:, 1]] = 1
```

**Comment by beat-buesser** [comment]
Hi @keykholt The proposed changes look good to me. Could you please make a fork and a pull request for these changes to branch `dev_1.1.0`?
