### ISSUE TITLE
ART attacks with Tensorflow-GPU support

### ISSUE THREAD

**Issue by MichaKh** [IBM/adversarial-robustness-toolbox#197]
Hi,

I have a question about the implementation of the attacks in ART.
I have a Keras model (wrapped in the KerasClassifier object) and I want to run the attacks with a Tensorflow-GPU backend. 
Do the attacks implementations support this? What do I have to do to support running with GPU?

Thanks

**Comment by beat-buesser** [comment]
Hi @MichaKh Thank you for using ART! Yes, all the attacks support GPUs. There are no additional settings required on the ART side. You just need to make sure that your machine learning library is installed in a version that supports GPUs (e.g. for TensorFlow version 1.14 and earlier as Keras backend use `tensorflow-gpu`, etc.).

**Comment by mingchangchiu** [comment]
A quick follow up. So as long as the Keras model is created on GPU like
` with tf.device('/gpu:0'): `
    `    model = create_model(og_size, nb_classes)  `
    `classifier = KerasClassifier(model=model, clip_values=(min_pixel_value, max_pixel_value), use_logits=False)
`

we can use directly
`  attack = HopSkipJump(classifier=classifier)`
`
  x_val_adv = attack.generate(x=x_val)`

Or we should use 
` with tf.device('/gpu:0'): ` again to make sure the attack run on GPU?

**Comment by beat-buesser** [comment]
@mingchangchiu If you want to run on a specific device and to be completely sure I would put all the code within the same `with tf.device:` block.

If you have only one device available, either becasue there is only one physical GPU or thorugh `CUDA_VISIBLE_DEVICES` only one is visible, you don't have to use `with tf.device:` as the framework behind ART will use GPUs if available.
