### ISSUE TITLE
Slack invite is stale

### ISSUE THREAD

**Issue by seanpmorgan** [IBM/adversarial-robustness-toolbox#203]
Hi All,

Thanks for the great work on this library. It appears the slack invite link on the central README is expired. Is there an alternative invite link?

![image](https://user-images.githubusercontent.com/18154355/68266903-7dee2780-001e-11ea-96f1-5578b2c6a341.png)

**Comment by beat-buesser** [comment]
Hi @seanpmorgan Thank you for alerting us about the inactive link, we'll try to fix it as soon as possible.

**Comment by beat-buesser** [comment]
The link should be working again.

**Comment by seanpmorgan** [comment]
Thanks!
