### ISSUE TITLE
Support for Pandas Dataframes and Set Preprocessing to None

### ISSUE THREAD

**Issue by keykholt** [IBM/adversarial-robustness-toolbox#205]
**Is your feature request related to a problem? Please describe.**
It seems like most (if not all) ART classes expect numpy array inputs in order to correctly create classifiers and adversarial samples. I've only noticed this issue occurring when creating classifiers or using some of the adversarial attacks. Issues I've run into occur because pandas dataframes have different indexing rules (e.g. using `.iloc[index]` instead of `[index]`) or are missing expected attributes (e.g. `dtype`).

The preprocessing parameter is set by default to (0,1), which indicates no change is made to the input. This causes some of the issues described above. Setting the value to None, causes it to skip the preprocessing step, which seems to behave equivalently to (0,1).

**Describe the solution you'd like**
Support for pandas dataframe inputs for ART classes. One way might be to create a separate input class, which checks the variable type (numpy array or dataframe) and handles it appropriately. This would be beneficial as new input variables can be added in a centralized location and gives users flexibility to add new custom input types.

**Additional context**
One way to reproduce the issue is to first create a classifier that accepts pandas dataframes. Convert it to an ART classifier. Then call either the `predict()` or `fit()` functions. An error will be thrown as part of the preprocessing step. In the preprocessing step, the code checks for the `dtype` attribute, which dataframes do not have. The current workaround is to set `preprocessing` to None.

Another issue arises in the Zoo attack. The code indexes the input on line 203 
`x_batch = x[batch_index_1:batch_index_2]`
For numpy arrays, it behaves as expected and returns an array slice with a len equal to the batch size. For pandas dataframes, it returns a 0 size array, which later causes an error on line 205 due to a 0 size array being passed.

**Comment by beat-buesser** [comment]
Hi @keykholt Thank you for proposing this very useful new feature and for working on implementing it! Let us know anytime if you need any help.
