### ISSUE TITLE
convert perturb into sphere in boundary attack.

### ISSUE THREAD

**Issue by AndrewSoul** [IBM/adversarial-robustness-toolbox#207]
**Describe the bug**
If the shape of perturb is (3,218,178) (channel, height, width), how to convert perturb （height and width are not equal) into sphere? 

**To Reproduce**
The shape of input image is (3,218,178) (channel, height, width). When I tried to run boundary attack, in function _orthogonal_perturb: it needed to convert perturb into sphere.
`perturb[i] -= np.dot(perturb[i], direction[i]) * direction[i]` 
But it failed because of the shape. How to deal with it ?
**Expected behavior**
Input image shape (3,218,178). Convert perturb into sphere for boundary attack.

**Screenshots**
This is screenshots:
![image](https://user-images.githubusercontent.com/18309839/68557802-e5b6cf00-0471-11ea-9693-10a3e9abed46.png)

**System information (please complete the following information):**
 - OS: ubuntu16.04
 - Python version: python 3.7
 - ART version: latest
 - PyTorch version:1.1

**Comment by beat-buesser** [comment]
Hi @AndrewSoul  Thank you very much for using ART and raising this issue! This would be for applications where the input images are not squares? If I'm right, I think so far we have tested ART only with square images, but I see an increasing interest in non-square shapes and ART. We'll take a look at it as soon as possible.
Would you have a proposal for a solution?
