### ISSUE TITLE
HCLU bug

### ISSUE THREAD

**Issue by KaGrosse** [IBM/adversarial-robustness-toolbox#208]
**Describe the bug**
The confidence parameter is hardcoded and not handed over to the method. See line 90 in the HCLU attack.

**Comment by KaGrosse** [comment]
Feel free to assign this to me, I'll fix this next Sunday. Sorry!

**Comment by beat-buesser** [comment]
@KaGrosse Thank you for finding the bug and working a solution! No worries!
