### ISSUE TITLE
The paper of Attack HopSkipJump

### ISSUE THREAD

**Issue by zhjikoshlizhzc** [IBM/adversarial-robustness-toolbox#209]
Hi!
I'm quite confused that what is the paper of the Attack HopSkipJump.

I can not find it,could you please show me it?

**Comment by beat-buesser** [comment]
Hi @zhjikoshlizhzc 

The paper for HopSkipJump is https://arxiv.org/abs/1904.02144
HopSkipJump was called Boundary Attack++ in early versions of that paper.

In ART, all methods include a link to a paper in their docstring/documentation, if possible.

**Comment by zhjikoshlizhzc** [comment]
Thanks a lot!
