### ISSUE TITLE
Which attacks have support for multi label in multiclass problem?

### ISSUE THREAD

**Issue by Shashikant255** [IBM/adversarial-robustness-toolbox#218]
Can any one please tell me which attacks have the support for multi-label in multi-class problem?
You can see in below images for reference:-
![Capture](https://user-images.githubusercontent.com/42666078/68938137-bed70080-07c3-11ea-966f-5a3f738f0ba0.PNG)

**Comment by beat-buesser** [comment]
Hi @Shashikant255 Thank you for using ART and raising and interesting question. As far as I know, we have tested ART only on single-label multi-class problems and that internally ART is expecting the labels to be one-hot-encoded or single index labels.
Could it be possible to create new labels representing pairs/triples/etc of your original labels?

**Comment by Shashikant255** [comment]
Hi @beat-buesser  Yes we can create new labels. But for many of cases we don't have much training example to train for those classes. So we have thought of having multi label.
Is there any way to modify the code to support multi-label for multi-class?

**Comment by beat-buesser** [comment]
I think it's definitely possible to modify/extend ART to work with multi-label data. One would probably have to start with looking at the methods `loss_gradient` and `class_gradient` of the classifier and make sure they can handle multi-label data. There are a few places in these methods that use for example `np.argmax` to find the index of the label, etc., therefore expecting a single label.
