### ISSUE TITLE
Run CarliniL2Method on GPU, 

### ISSUE THREAD

**Issue by Jindong-Explainable-AI** [IBM/adversarial-robustness-toolbox#22]
img_adv = adv.generate(img_variable.data.numpy())
  File "/usr/local/lib/python2.7/dist-packages/art/attacks/carlini.py", line 184, in generate
    grad_l2p = self.classifier.class_gradient(np.array([adv_image]), label=i_add, logits=True)[0]
  File "/usr/local/lib/python2.7/dist-packages/art/classifiers/pytorch.py", line 211, in class_gradient
    torch.autograd.backward(preds[:, label], torch.Tensor([1.] * len(preds[:, 0])), retain_graph=True)
  File "/usr/local/lib/python2.7/dist-packages/torch/autograd/__init__.py", line 90, in backward
    allow_unreachable=True)  # allow_unreachable flag
RuntimeError: invalid gradient at index 0 - expected type torch.cuda.FloatTensor but got torch.FloatTensor

To produce the error:
classifier = PyTorchClassifier(clip_values=(-2.11790394, 2.2489084), model=model, loss= nn.CrossEntropyLoss(),
                               optimizer= torch.optim.SGD(model.parameters(), lr = 0.01),
                               input_shape=(3, 224, 224), nb_classes = 1000, defences = None, preprocessing=(0, 1))

adv = CarliniL2Method(classifier, targeted=False, max_iter=10, binary_search_steps=10, learning_rate=0.01)

img_adv = adv.generate(image a numpy array)

When running on a GPU, it will an error. No problem on a CPU.
Thanks for talking this issue!

**Comment by ririnicolae** [comment]
This issue has been solved in f524fb1. Please let us know if you encounter further problems.
