### ISSUE TITLE
Cannot import name 'SklearnClassifier'

### ISSUE THREAD

**Issue by yzhang017** [IBM/adversarial-robustness-toolbox#222]
I followed the Setup instruction using pip to install this toolbox on the Jupyter Notebook 6.0.2. But when I run examples with Python 3, it has error. 

from sklearn.svm import SVC
import numpy as np

from art.attacks import FastGradientMethod
from art.classifiers import SklearnClassifier
from art.utils import load_mnist

ImportError:  **cannot import name 'SklearnClassifier'** .  

Did anyone occur this before?

**Comment by beat-buesser** [comment]
Hi @yzhang017 Thank you very much for using ART and raising this question! Could you please describe your operating system and where did you run the pip command?

**Comment by yzhang017** [comment]
I have  the latest version of Anaconda on Windows 10 and run pip command in the Anaconda prompt.

**Comment by beat-buesser** [comment]
Could you please run `pip freeze` and post its output? Could you also show how you run the examples?

**Comment by yzhang017** [comment]
The following is the output from pip freeze:
absl-py==0.7.1
ad3==2.2.1
Adversarial-Robustness-Toolbox==0.9.0
aiohttp==3.5.4
anaconda-client==1.7.2
anaconda-navigator==1.9.7
asn1crypto==1.2.0
astor==0.7.1
async-timeout==3.0.1
attrs==19.3.0
backcall==0.1.0
backports.functools-lru-cache==1.6.1
backports.tempfile==1.0
backports.weakref==1.0.post1
beautifulsoup4==4.8.1
bleach==3.1.0
certifi==2019.9.11
cffi==1.13.2
chardet==3.0.4
Click==7.0
clyent==1.2.2
colorama==0.4.1
conda==4.7.12
conda-build==3.0.22
conda-package-handling==1.6.0
conda-verify==3.4.2
cryptography==2.8
cvxopt==1.2.0
cycler==0.10.0
decorator==4.4.1
defusedxml==0.6.0
discord.py==1.2.3
entrypoints==0.3
filelock==3.0.12
future==0.18.2
gast==0.2.2
glob2==0.7
grpcio==1.19.0
idna==2.8
idna-ssl==1.1.0
importlib-metadata==0.23
ipykernel==5.1.3
ipython==7.9.0
ipython-genutils==0.2.0
ipywidgets==7.5.1
jedi==0.15.1
Jinja2==2.10.3
joblib==0.14.0
jsonschema==3.2.0
jupyter==1.0.0
jupyter-client==5.3.4
jupyter-console==6.0.0
jupyter-core==4.6.1
jupytext==1.2.4
Keras==2.0.9
Keras-Applications==1.0.7
Keras-Preprocessing==1.0.9
kiwisolver==1.1.0
Markdown==3.1
MarkupSafe==1.1.1
matplotlib==3.1.1
menuinst==1.4.16
mistune==0.8.4
mkl-fft==1.0.15
mkl-random==1.1.0
mkl-service==2.3.0
mock==2.0.0
more-itertools==7.2.0
multidict==4.5.2
nbconvert==5.6.1
nbformat==4.4.0
networkx==2.4
notebook==6.0.2
numpy==1.17.3
olefile==0.46
opencv-python==4.0.0.21
pandas==0.25.3
pandocfilters==1.4.2
parso==0.5.1
pbr==5.1.3
pickleshare==0.7.5
Pillow==6.2.1
pkginfo==1.5.0.1
prometheus-client==0.7.1
prompt-toolkit==2.0.10
protobuf==3.7.0
psutil==5.6.5
pycosat==0.6.3
pycparser==2.19
Pygments==2.4.2
pyOpenSSL==19.1.0
pyparsing==2.4.5
pyrsistent==0.15.5
PySocks==1.7.1
pystruct==0.3.2
python-dateutil==2.8.1
pytz==2019.3
pywin32==223
pywinpty==0.5.5
PyYAML==5.1.2
pyzmq==18.1.0
qtconsole==4.6.0
QtPy==1.9.0
requests==2.22.0
ruamel-yaml==0.15.46
scikit-learn==0.21.3
scikit-multiflow==0.4.1
scipy==1.3.2
Send2Trash==1.5.0
six==1.13.0
sortedcontainers==2.1.0
soupsieve==1.9.5
tensorboard==1.13.1
tensorflow==1.13.1
tensorflow-estimator==1.13.0
termcolor==1.1.0
terminado==0.8.3
testfixtures==6.10.2
testpath==0.4.4
tornado==6.0.3
tqdm==4.38.0
traitlets==4.3.3
typing-extensions==3.7.4
urllib3==1.24.2
wcwidth==0.1.7
webencodings==0.5.1
websockets==6.0
widgetsnbextension==3.5.1
win-inet-pton==1.1.0
wincertstore==0.2
yarl==1.3.0
zipp==0.6.0
Note: you may need to restart the kernel to use updated packages.
Could not parse requirement: -umpy
Could not parse requirement: -illow

Here is the code I run in jupyter notebook and the error:  
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix
from sklearn.preprocessing import StandardScaler

from art.attacks import FastGradientMethod
from art.classifiers import SklearnClassifier

---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-95a3dc4d99b1> in <module>
      4 
      5 from art.attacks import FastGradientMethod
----> 6 from art.classifiers import SklearnClassifier

ImportError: cannot import name 'SklearnClassifier'

**Comment by beat-buesser** [comment]
Thank you! I see that you have installed `Adversarial-Robustness-Toolbox==0.9.0`. The support for scikit-learn has been introduced with ART v1.0. If you upgrade your installation of ART to v1.0 the error should disappear.

**Comment by yzhang017** [comment]
Thank you so much. It fixed. Actually, I installed the ART yesterday, so I did not realize it needs to be upgraded.
