### ISSUE TITLE
Add new check to EnsembleClassifier and its classifiers for identical channel_index

### ISSUE THREAD

**Issue by dapello** [IBM/adversarial-robustness-toolbox#223]
**Describe the bug**
The SpatialTransform attack does not properly rotate / translate images formatted for an ensemble of Pytorch models. Judging by the outputs, I think somewhere along the line the channels are not being handled correctly. Note, for an ensemble of Keras models, the attack seems to work fine.

**To Reproduce**
```
import torch
from torchvision import models

from art.classifiers import PyTorchClassifier, EnsembleClassifier
from art.attacks import SpatialTransformation

# load and preprocess imagenet images
images = load_preprocess_images(...)

resnet18 = models.resnet18(pretrained=True)
alexnet = models.alexnet(pretrained=True)

wrapped_models = []
for model in [resnet18, alexnet]:
    loss = torch.nn.CrossEntropyLoss()
    optimizer = torch.optim.SGD(model.parameters(), .1, momentum=0.9, weight_decay=1e-4)
    wrapped_model = PyTorchClassifier(model=model, loss=loss, optimizer=optimizer, input_shape=(3,224,224), nb_classes=1000)
    wrapped_models.append(wrapped_model)
    
ensemble = EnsembleClassifier(wrapped_models)
attack = SpatialTransformation(ensemble, max_translation=10, num_translations=5, max_rotation=10, num_rotations=5)
adv_images = attack.generate(x = images)
```

example input and output images:
![image](https://user-images.githubusercontent.com/8093360/69280973-6d5cb600-0bb5-11ea-93a2-54ef7b7d0c4e.png)

**Expected behavior**
example input and expected output images:
![image](https://user-images.githubusercontent.com/8093360/69280640-d132af00-0bb4-11ea-8651-33f651bc6670.png)
![image](https://user-images.githubusercontent.com/8093360/69280650-d8f25380-0bb4-11ea-9e2d-d94e5ecffa1d.png)

**System information (please complete the following information):**
 - Fedora Linux
 - Python 3.6.7
 - ART 1.0.1
 - PyTorch 1.2.0

**Comment by beat-buesser** [comment]
Hi @dapello Thank you for raising this issue! Do you also observe this unexpected behaviour of `SpatialTransformation` if you use `PyTorchClassifier` without `EnsembleClassifier`?

**Comment by dapello** [comment]
Hi @beat-buesser, in my experience it only happens with the ensemble of pytorch classifiers -- using a single `PyTorchClassifier` behaved as expected.

**Comment by beat-buesser** [comment]
Can you try setting the argument `channel_index=1` in `EnsembleClassifier`?

**Comment by dapello** [comment]
Ah, that fixed it! Thank you.
