### ISSUE TITLE
Investigate logging output for tests

### ISSUE THREAD

**Issue by ririnicolae** [IBM/adversarial-robustness-toolbox#227]
The output from some unit tests seems to be present in Travis logs, while others are missing. This is in spite of the fact that all tests are configured the same. The purpose of this issue is to investigate this and to fix it if necessary.

Reported by @beat-buesser

**Comment by beat-buesser** [comment]
I think some of the changes to `.travis.yml` in PR #265 have fixed the missing logging messages, but I'm not exactly sure why, maybe because the tests are now running in the virutalenv of Travis instead of conda.
