### ISSUE TITLE
Models in Caffe

### ISSUE THREAD

**Issue by rajasekharponakala** [IBM/adversarial-robustness-toolbox#23]
Hey folks!

This project is a great effort. Similar way, can we pass Caffe models to this tool?

Thanks

**Comment by ririnicolae** [comment]
Hi, @rajasekharponakala! We don't currently support Caffe models, but we gladly accept contributions and extensions if you have some time to spend on this!

**Comment by rajasekharponakala** [comment]
hi @ririnicolae: Sure, I want to contribute. Could you guide me!

Thanks.

**Comment by ririnicolae** [comment]
Sure, that would be great! Overall, you need to provide a wrapper on top of a Caffe model called `CaffeClassifier`. This wrapper implements the `Classifier` API from `art/classifiers/classifier.py` (see doc [here](https://adversarial-robustness-toolbox.readthedocs.io/en/latest/modules/classifiers.html#base-class)). Notice that the data types used by model wrappers are standard Python types and Numpy arrays. The Caffe wrapper should go in `art/classifiers/caffe.py`, and you should provide unit tests in `art/classifiers/caffe_unittest.py`.

We can take this to [Slack](https://join.slack.com/t/ibm-art/shared_invite/enQtMzkyOTkyODE4NzM4LTlkMWY3MzgyZDA4ZDdiNzUzY2NhMjc5YmFhZTYzZGYwNDM4YTE1ODhhNDYyNmFlMGFjNWY4ODgyM2EwYTFjYTc) for a detailed discussion!

**Comment by rajasekharponakala** [comment]
@ririnicolae: Thanks again. I'm already in there and let's catch-up there!

**Comment by beat-buesser** [comment]
I'm closing this issue because development in Caffe seem to have stopped and Caffe2 has been merged with PyTorch (https://medium.com/@Synced/caffe2-merges-with-pytorch-a89c70ad9eb7). @hesseltuinhof Thank you for the hint.
