### ISSUE TITLE
Enable import of full ART package

### ISSUE THREAD

**Issue by seanpmorgan** [IBM/adversarial-robustness-toolbox#235]
**Is your feature request related to a problem? Please describe.**
It would be nice to be able to import the full ART toolkit using `import art`

However, the import structure does not allow this:
```
import art
wrapper = art.classifiers.KerasClassifier(model=dummy_model)
```
Returns `AttributeError: module 'art' has no attribute 'classifiers'`

See: 
https://colab.research.google.com/drive/1X3U0xm0uEEwWDM4njwwbl9aDK5Jk9OeO

I would be willing to submit a PR for this but wanted to check with the maintainers to see if there is a reason for this.

**Comment by beat-buesser** [comment]
Hi @seanpmorgan Thank you for opening this issue. I don't think there is a specific reason why we don't support it so far. It would be great if you could make a PR for this. I'll assign this issue to you.
