### ISSUE TITLE
Add version to ART package

### ISSUE THREAD

**Issue by seanpmorgan** [IBM/adversarial-robustness-toolbox#236]
**Describe the bug**
Per [PEP 396](https://www.python.org/dev/peps/pep-0396/) it's beneficial for users to be able to programatically check module version using `__version__`.

**To Reproduce**
```
import art
art.__version__
```
Returns:
`AttributeError: module 'art' has no attribute '__version__'`

I'd be willing to submit a PR, but want to make sure there isn't some reason for this.

**System information (please complete the following information):**
 - OS: Ubuntu 18.04
 - Python version: All
 - ART version or commit number: 1.0

**Comment by beat-buesser** [comment]
Hi @seanpmorgan I agree, we should support `__version__`. Please go ahead with the PR.
