### ISSUE TITLE
Unable to load_model !!!!

### ISSUE THREAD

**Issue by Luke06** [IBM/adversarial-robustness-toolbox#24]
I wrote a sample notebook in python to test the models provided and run the samples notebooks, but none of them are being loaded correctly when invoked.
here is the python snippet I used

from keras.models import load_model
....
!wget 'https://github.com/IBM/adversarial-robustness-toolbox/blob/master/models/mnist_cnn_original.h5'
!ls -l
Saving to: ‘mnist_cnn_original.h5’

    [ <=>                                   ] 44,357      --.-K/s   in 0.06s   

2018-10-30 16:11:29 (725 KB/s) - ‘mnist_cnn_original.h5’ saved [44357]

total 88
-rw-r----- 1 dsxuser dsxuser 44357 Oct 30 16:06 mnist_cnn_original.h5

classifier = load_model("mnist_cnn_original.h5")
...
/opt/conda/envs/DSX-Python35/lib/python3.5/site-packages/h5py/_hl/files.py in make_fid(name, mode, userblock_size, fapl, fcpl, swmr)
     99         if swmr and swmr_support:
    100             flags |= h5f.ACC_SWMR_READ
--> 101         fid = h5f.open(name, flags, fapl=fapl)
    102     elif mode == 'r+':
    103         fid = h5f.open(name, h5f.ACC_RDWR, fapl=fapl)

h5py/_objects.pyx in h5py._objects.with_phil.wrapper()

h5py/_objects.pyx in h5py._objects.with_phil.wrapper()

h5py/h5f.pyx in h5py.h5f.open()

OSError: Unable to open file (File signature not found)

SO THE FILE IS FOUND BUT SOMETHING WRONG WITH THE FORMAT !!!
THANKS in advance

**Comment by ririnicolae** [comment]
Hi, @Luke06! Please see the following comment about how to download `h5` files without corrupting their integrity: https://github.com/h5py/h5py/issues/757#issuecomment-412287475 Let me know if this solves the issue. Also, the model was created with `keras==2.2.2`; please consider using the same version to make sure that you can load it.

**Comment by Luke06** [comment]
Hi
I looked at the comment but I don't see how it fix my problem ,  Iam using the std keras library to load the model and the file is they one from the ART repo that I retrieve thru a wget in my python notebook. the downloaded file seems to be correct. I am in Keras 2.2.4 ! but cannot move back to 2.2.2 due to others incompatibilities in my code :(. in fact my goal is to retrain my model using your defence training libraries but it was not working neither so....

**Comment by ririnicolae** [comment]
@Luke06 I have tested your scenario. Loading the model does not work for me neither if I download it using `wget`. Actually, the model from the repo and the one downloaded with `wget` don't even have the same size on disk (I get 44357 for `wget`, just the same as you, and 2737408 for the model downloaded properly). That is what the comment I pointed you towards explains. You could clone the repo or use the solution in the comment to make sure you get a valid version of the file.

On a different note, if your goal is to train an architecture that you already have with the defenses from the library, you don't necessarily need to download the pre-trained models that we use as examples.

**Comment by Luke06** [comment]
OK I understand the problem with the downloaded h5 file.
Yes my initial goal was to retrain my model using the defences from the libraries but  I was encountering some issues probably due to invalid usage of the library, here is the code I tried to use 
I have defined a CNN model called model and I create a Classifier wrapper :
Original_Classifier = KerasClassifier((0,1),model,use_logits=False)
Original_Classifier.fit(x_train, y_train, batch_size=128, nb_epochs=10)

Then I tried this lines that I found in the notebook sample called adversarial-training-mnist.ipynb

attacks = BasicIterativeMethod(Original_Classifier,eps=0.3,eps_step=0.01, max_iter=40)
trainer = AdversarialTrainer(Original_Classifier,attacks,ratio=1.0)
trainer.fit(x_train,y_train, nb_epochs=10,batch_size=50)

but the training ended after the 1 epochs with very strange results.
Can you pls provide me with the right way & sample code of doing that for my training against Fast Gradient Method attack ? 
by advance thanks a lot

**Comment by ririnicolae** [comment]
I would say that your original problem (`.h5` files) is solved, so I will close this issue.

I don't see any obvious error in your code example. Would you mind opening a new issue for it, where you would copy the code example, as well as the full stack trace of the error you are getting when running it?
