### ISSUE TITLE
Investigate @tf.function models running as a wrapped classifier

### ISSUE THREAD

**Issue by seanpmorgan** [IBM/adversarial-robustness-toolbox#245]
Per #243 we should investigate to see any issues that occur for models that utilize `@tf.function` which are wrapped by the TensorFlowV2Classifer. 

You can assign this issue to me.

**Comment by beat-buesser** [comment]
@seanpmorgan Thank you for looking into this issue.

**Comment by seanpmorgan** [comment]
So I had a chance to look into this a bit...

There should be no issues since gradient tape is able to trace anything decorated with `@tf.function`. 
```python
(x_train, y_train), (x_test, y_test), _, _ = load_mnist()


class TensorFlowModel(Model):
    """
    Standard TensorFlow model for unit testing
    """
    def __init__(self):
        super(TensorFlowModel, self).__init__()
        self.conv1 = Conv2D(filters=1, kernel_size=7, activation='relu')
        self.maxpool = MaxPool2D(pool_size=(4, 4), strides=(4, 4), padding='valid', data_format=None)
        self.flatten = Flatten()
        self.dense1 = Dense(10, activation='softmax')

    @tf.function
    def custom_thing(self, x):
        x += tf.constant(10.0)
        return x

    def call(self, x):
        """
        Call function to evaluate the model
        :param x: Input to the model
        :return: Prediction of the model
        """
        x = self.conv1(x)
        x = self.maxpool(x)
        x = self.flatten(x)
        x = self.custom_thing(x)
        x = self.dense1(x)
        return x


if __name__ == "__main__":
    model = TensorFlowModel()
    loss_object = tf.keras.losses.SparseCategoricalCrossentropy()

    # Create the classifier
    tfc = TensorFlowV2Classifier(model=model, loss_object=loss_object, nb_classes=10, input_shape=(28, 28, 1),
                                 clip_values=(0, 1))

    y_predicted = tfc.predict(x_test[0:1])
    grad = tfc.class_gradient(x_test[0:1], label=0)
    print(y_predicted)
    print(grad)
```

**Comment by seanpmorgan** [comment]
However, while using this wrapper I found it very un-intuitive for the typical TF2 Keras subclass paradigm. For example:

The above code but running:
```
tfc.fit(x_train, y_train, batch_size=64, nb_epochs=3)
```
Will return:
```
# self._train_step(images, labels)
# TypeError: 'NoneType' object is not callable
```
A user could specify a `_train_step`,  but that's a strange function to write because having that determined for you is one of the major reasons to be using Keras models in the first place.

I'm going to close this issue as `@tf.function` doesn't seem to be causing issues with the wrapper, but I'll continue discussion in #243 about a possible refactor.

**Comment by beat-buesser** [comment]
@seanpmorgan Thank you very much for looking into this issue and please apologise the delayed response.
