### ISSUE TITLE
 AttributeError: 'TensorFlowV2Classifier' object has no attribute '_input_shape'

### ISSUE THREAD

**Issue by ashishcse0031** [IBM/adversarial-robustness-toolbox#246]
AttributeError                            Traceback (most recent call last)
<ipython-input-29-2bb3f266838f> in <module>()
      1 virtual_adversarial_method = VirtualAdversarialMethod(classifier, max_iter=10, finite_diff=1e-06, eps=0.1, batch_size=1)
      2 
----> 3 data_adv = virtual_adversarial_method.generate(x_test[:10])
      4 
      5 plt.imshow(data_adv[0].reshape(28, 28))

1 frames
/usr/local/lib/python3.6/dist-packages/art/classifiers/classifier.py in input_shape(self)
    125         :rtype: `tuple`
    126         """
--> 127         return self._input_shape
    128 
    129     @abc.abstractmethod

AttributeError: 'TensorFlowV2Classifier' object has no attribute '_input_shape'

**Comment by beat-buesser** [comment]
Hi @ashishcse0031 Thank you very much for using ART and reporting this issue! We will investigate and fix it as soon as possible.

**Comment by seanpmorgan** [comment]
@beat-buesser I believe this can be closed since #249?

**Comment by beat-buesser** [comment]
Thank you all. I used to keep the issues open until their solutions made it to master branch to avoid duplicate issues, but I'm open to adapt the issues process since we are tracking progression now with projects/milestones.
