### ISSUE TITLE
Any adversarial attack that sustains after resize attack

### ISSUE THREAD

**Issue by BalaMallikarjuna-G** [IBM/adversarial-robustness-toolbox#247]
Hi,

 I have a query regarding adversarial attack.

Is there any adversarial attack that sustains/consists of added noise, after resize attack ? (adversarial image -> converting into High / low resolution image -> resize to original adverarial image size)

Thanks,
Bala

**Comment by mathsinn** [comment]
Hi @BalaMallikarjuna-G , thank you for your interest in using ART and in your inquiry.

If I understand correctly, your question is how to create an adversarial example that results in a targeted/untargeted misclassification even after being converted into high/low resolution image and then being resized to the original image size?

The common approach to accomplish this is via partial backpropagation of gradients (see https://arxiv.org/abs/1802.00420). ART supports this out of the box. E.g. see this notebook for an example: https://github.com/IBM/adversarial-robustness-toolbox/blob/master/notebooks/attack_defence_imagenet.ipynb

It shows how to create adversarial examples that "survive" a spatial smoothing defence.

In your case, all you need to do is to implement a resizing defence, equivalent to https://github.com/IBM/adversarial-robustness-toolbox/blob/master/art/defences/spatial_smoothing.py . Then, when you attack a classifier that uses this defence, the attack will try to make the adversarial examples sustain the defence.

Hope this helps, and please let us know how it works for you.

**Comment by BalaMallikarjuna-G** [comment]
Hi Sir,
Sorry for the late reply. I was out of work for last few days.
Thanks for your reply . I will check and get back to you.
