### ISSUE TITLE
Accept soft labels in the fit function of ART classifier

### ISSUE THREAD

**Issue by minhitbk** [IBM/adversarial-robustness-toolbox#251]
Currently the fit function of an ART classifier just accepts either index labels or 1-hot labels and doen't accept probability labels. In learning-based extraction attacks, victim models may return probability labels which contain many useful information that can be harnessed by a thieved model. So ART classifier needs to accept probability labels in the fitting function.

**Comment by beat-buesser** [comment]
@minhitbk Thank you very much for raising this issue!
