### ISSUE TITLE
trying AdversarialPatch attack and I get 'tuple' object has no attribute 'dtype' error

### ISSUE THREAD

**Issue by teavanist** [IBM/adversarial-robustness-toolbox#252]
Hi, 
I am trying to run the AdversarialPatch attack using a variation of the code from Pytorch and the ART examples. But I get the following error: 
AttributeError: 'tuple' object has no attribute 'dtype'
The same code works correctly with FastGradientMethod and CarliniL2Method attack. Am I doing anything wrong? Or rather should anything be done differently for AdversarialPatch attacks? 
Below is the full code, I have also attached my Jupyter notebook:
------------
# LeNet Model definition
class LeNet5(nn.Module):
    def __init__(self):
        super(LeNet5, self).__init__()
        self.conv1 = nn.Conv2d(1, 10, kernel_size=5)
        self.conv2 = nn.Conv2d(10, 20, kernel_size=5)
        self.conv2_drop = nn.Dropout2d()
        self.fc1 = nn.Linear(320, 50)
        self.fc2 = nn.Linear(50, 10)

    def forward(self, x):
        x = F.relu(F.max_pool2d(self.conv1(x), 2))
        x = F.relu(F.max_pool2d(self.conv2_drop(self.conv2(x)), 2))
        x = x.view(-1, 320)
        x = F.relu(self.fc1(x))
        x = F.dropout(x, training=self.training)
        x = self.fc2(x)
        return F.log_softmax(x, dim=1)

    
#Location for pre-trained model: 
#url="https://drive.google.com/drive/folders/1fn83DF14tWmit0RTKWRhPq5uVXt73e0h?usp=sharing"
#Saved in  "Models/lenet_mnist_model.pth"

    
pretrained_model = "Models/lenet_mnist_model.pth"
use_cuda=False
    
    
# Define what device we are using
print("CUDA Available: ",torch.cuda.is_available())
#device = torch.device("cuda" if (use_cuda and torch.cuda.is_available()) else "cpu")
device = torch.device("cuda" if (torch.cuda.is_available()) else "cpu")

# Initialize the network
model = LeNet5().to(device)

# Load the pretrained model
model.load_state_dict(torch.load(pretrained_model, map_location='cpu'))

# Set the model in evaluation mode. In this case this is for the Dropout layers
model.eval()

# =============================
def ART_x_y_generator(dataset):
    '''
    will convert a PyTorch dataset to the format required by IBM ART for data processing 
    
    '''
    data_loader = torch.utils.data.DataLoader(dataset, batch_size=len(dataset))

    images = next(iter(data_loader))[0].numpy()
    
    labels = np.full((len(dataset),10),0.0,dtype="float32")
    
    target_list = dataset.targets.numpy()
    
    for index, target in enumerate(target_list):
        labels[index][target]=1
        
    return images, labels 
# =============================
# Create x_train and y_train 
train_dataset = datasets.MNIST('data/MNIST/', train=True, download=True, transform=transforms.Compose([
            transforms.ToTensor(),
            ]))

x_train, y_train = ART_x_y_generator(train_dataset)

# Create x_test and y_test 
test_dataset = datasets.MNIST('data/MNIST/', train=False, download=True, transform=transforms.Compose([
            transforms.ToTensor(),
            ]))

x_test, y_test = ART_x_y_generator(test_dataset)
# =============================
criterion = nn.CrossEntropyLoss()
optimizer = optim.SGD(model.parameters(), lr=0.01, momentum=0.5)

# Step 3: Create the ART classifier
min_pixel_value=0.0
max_pixel_value=1.0 

classifier = PyTorchClassifier(model=model
                               , clip_values=(min_pixel_value, max_pixel_value)
                               , loss=criterion
                               , optimizer=optimizer
                               , input_shape=(1, 28, 28)
                               , nb_classes=10)

# =============================
# Use a small subset for demonstration purposes 
x_test_limited = x_test[:32]
y_test_limited = y_test[:32]

# Generate adversarial test examples and show effectiveness 
start_time = time.time()
attack = AdversarialPatch(classifier=classifier)
x_test_adv = attack.generate(x=x_test_limited)
predictions = classifier.predict(x_test_adv)
accuracy = np.sum(np.argmax(predictions, axis=1) == np.argmax(y_test_limited, axis=1)) / len(y_test_limited)
print('Accuracy on adversarial test examples: {}%'.format(accuracy * 100))
print("--- %s seconds ---" % (time.time() - start_time))

[ART v3.zip](https://github.com/IBM/adversarial-robustness-toolbox/files/4000638/ART.v3.zip)

**Comment by teavanist** [comment]
Below is the full error: 
-----------
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-33-e63d05675337> in <module>
      3 attack = AdversarialPatch(classifier=classifier)
      4 x_test_adv = attack.generate(x=x_test_limited)
----> 5 predictions = classifier.predict(x_test_adv)
      6 accuracy = np.sum(np.argmax(predictions, axis=1) == np.argmax(y_test_limited, axis=1)) / len(y_test_limited)
      7 print('Accuracy on adversarial test examples: {}%'.format(accuracy * 100))

c:\program files\python37\lib\site-packages\art\classifiers\pytorch.py in predict(self, x, batch_size, **kwargs)
    104 
    105         # Apply preprocessing
--> 106         x_preprocessed, _ = self._apply_preprocessing(x, y=None, fit=False)
    107 
    108         # Run prediction with batch processing

c:\program files\python37\lib\site-packages\art\classifiers\classifier.py in _apply_preprocessing(self, x, y, fit)
    166         y = check_and_transform_label_format(y, self.nb_classes())
    167         x_preprocessed, y_preprocessed = self._apply_preprocessing_defences(x, y, fit=fit)
--> 168         x_preprocessed = self._apply_preprocessing_standardisation(x_preprocessed)
    169         return x_preprocessed, y_preprocessed
    170 

c:\program files\python37\lib\site-packages\art\classifiers\classifier.py in _apply_preprocessing_standardisation(self, x)
    205         if self.preprocessing is not None:
    206             sub, div = self.preprocessing
--> 207             sub = np.asarray(sub, dtype=x.dtype)
    208             div = np.asarray(div, dtype=x.dtype)
    209 

AttributeError: 'tuple' object has no attribute 'dtype'

**Comment by teavanist** [comment]
Hi guys,
Anyone looking at this?

**Comment by mathsinn** [comment]
Hi @teavanist 

Thank you for using ART and raising this issue! Apologies for not getting back to you earlier. 

Please take a look at this notebook, which shows how to create adversarial patches with ART: https://github.com/IBM/adversarial-robustness-toolbox/blob/master/notebooks/attack_adversarial_patch.ipynb

As you can see there, the `attack.generate` function returns a tuple, not a numpy array as for other attacks, and an extra step (via the `.apply` function) is required to apply the created patch to an image.

Please let us know whether this helps or you still run into problems.

**Comment by teavanist** [comment]
Thanks @mathsinn I will check this
