### ISSUE TITLE
Missing documentation about SVM attack

### ISSUE THREAD

**Issue by teavanist** [IBM/adversarial-robustness-toolbox#253]
![2019-12-26 01_01_05-art attacks — Adversarial Robustness Toolbox 1 0 1 documentation](https://user-images.githubusercontent.com/37803648/71450439-55abbb00-277b-11ea-91b8-f954293e0d7d.jpg)
The documentation about SVM attacks seem to be missing from the below link. Do have a look. 

https://adversarial-robustness-toolbox.readthedocs.io/en/latest/modules/attacks.html#svm-attack

**Comment by beat-buesser** [comment]
Hi @teavanist Thank you very much for using ART and pointing out the missing documentation! We will add it as soon as possible.
