### ISSUE TITLE
VirtualAdversarialMethod - error - Values smaller than 0.0 or larger than 1.0 have been detected

### ISSUE THREAD

**Issue by teavanist** [IBM/adversarial-robustness-toolbox#263]
Hi, 
I am running the VirtualAdversarialMethod and I get a "Values smaller than 0.0 or larger than 1.0 have been detected". My predictions include negative values. How do I tell the classifier to convert the predictions to values between 0 and 1? I did not see any option for this in the documentation. 

===== Error message ============
c:\program files\python37\lib\site-packages\art\attacks\virtual_adversarial.py in generate(self, x, y, **kwargs)
     84         preds = self.classifier.predict(x_adv, batch_size=self.batch_size)
     85         if (preds < 0.0).any() or (preds > 1.0).any():
---> 86             raise TypeError('This attack requires a classifier predicting probabilities in the range [0, 1] as output.'
     87                             'Values smaller than 0.0 or larger than 1.0 have been detected.')
     88         # preds_rescaled = self._rescale(preds) # Rescaling needs more testing

TypeError: This attack requires a classifier predicting probabilities in the range [0, 1] as output.Values smaller than 0.0 or larger than 1.0 have been detected.

**Comment by teavanist** [comment]
I think the following code should resolve the issue but I dont know where to use this. 

new_predictions = []
for prediction in predictions: 
    # Normalised [0,1]
    new_prediction = (prediction - np.min(prediction))/np.ptp(prediction)
    normalized_predictions.append(normalized_prediction)

**Comment by teavanist** [comment]
I am including the Jupyter notebook for your reference and reproduction . 
[VirtualAdversarialMethod copy.zip](https://github.com/IBM/adversarial-robustness-toolbox/files/4058441/VirtualAdversarialMethod.copy.zip)

**Comment by beat-buesser** [comment]
Hi @teavanist Thank you for using ART and your question! Let me take a look at your notebook.

**Comment by beat-buesser** [comment]
`VirtualAdversarialMethod` currently only supports models predicting probabilities. It looks like your model does not predict probabilities. The model in the notebook seems to make predictions in the range -33.97 to 0.0.

**Comment by teavanist** [comment]
Thanks

**Comment by teavanist** [comment]
@beat-buesser  whats a good way to reach out to you privately? We are doing a project at our University and it involves IBM ART. I wanted to discuss some of our findings with you.

**Comment by beat-buesser** [comment]
@teavanist We have a workspace on Slack at ibm-art.slack.com, the invitation link is on the README of the master branch. There we can discuss either on open channels or with direct messages.

**Comment by Nancis1130** [comment]
Hi @teavanist, how you ultimately resolved it? Thanks.
