### ISSUE TITLE
MSE function

### ISSUE THREAD

**Issue by khedher1984** [IBM/adversarial-robustness-toolbox#278]
Hello,
I have a model compiled with the MSE loss function.
I could not use the tool because the function is not implemented.
Have you any suggestions?
Thank you

**Comment by beat-buesser** [comment]
Hi @khedher1984 Thank you for using ART and raising this issue! Could you please provide additional information which classes of ART you are using or better a short code example?

**Comment by khedher1984** [comment]
Thank you for your help.
I used the MNIST dataset to create a classification model based on the MSE loss function.
My architecutre is the following:

from __future__ import print_function
import keras
from keras.datasets import mnist
from keras.models import Sequential
from keras.layers import Dense, Dropout, Flatten
from keras.layers import Conv2D, MaxPooling2D
from keras import backend as K

batch_size = 128
num_classes = 10
epochs = 2

# input image dimensions
img_rows, img_cols = 28, 28

# the data, shuffled and split between train and test sets
(x_train, y_train), (x_test, y_test) = mnist.load_data()

if K.image_data_format() == 'channels_first':
    x_train = x_train.reshape(x_train.shape[0], 1, img_rows, img_cols)
    x_test = x_test.reshape(x_test.shape[0], 1, img_rows, img_cols)
    input_shape = (1, img_rows, img_cols)
else:
    x_train = x_train.reshape(x_train.shape[0], img_rows, img_cols, 1)
    x_test = x_test.reshape(x_test.shape[0], img_rows, img_cols, 1)
    input_shape = (img_rows, img_cols, 1)

x_train = x_train.astype('float32')
x_test = x_test.astype('float32')
x_train /= 255
x_test /= 255
print('x_train shape:', x_train.shape)
print(x_train.shape[0], 'train samples')
print(x_test.shape[0], 'test samples')

# convert class vectors to binary class matrices
y_train = keras.utils.to_categorical(y_train, num_classes)
y_test = keras.utils.to_categorical(y_test, num_classes)

model = Sequential()
model.add(Conv2D(32, kernel_size=(3, 3),
                 activation='relu',
                 input_shape=input_shape))
model.add(Conv2D(64, (3, 3), activation='relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))
model.add(Dropout(0.25))
model.add(Flatten())
model.add(Dense(128, activation='relu'))
model.add(Dropout(0.5))
model.add(Dense(num_classes, activation='softmax'))

model.compile(loss=keras.losses.mean_squared_error,
              optimizer=keras.optimizers.Adadelta(),
              metrics=['accuracy'])

model.fit(x_train, y_train,
          batch_size=batch_size,
          epochs=epochs,
          verbose=1,
          validation_data=(x_test, y_test))

model.save('mnist_mse.h5')


When, I apply the Keras classifier, I have the folloing error message:

AttributeError: module 'keras.backend' has no attribute 'mean_squared_error'

Thank you in advace for your help

**Comment by beat-buesser** [comment]
@khedher1984 Thank you for the detailed code example! The loss function `keras.losses.mean_squared_error` is not supported in the current version of `KerasClassifier`, but we plan to support it in the upcoming releases of ART.

Your example does work with `KerasClassifier` after changing to categorical crossentropy with `model.compile(loss=keras.losses.categorical_crossentropy,` and achieves even better accuracy on the original dataset.

If you need to use mean squared error you would have to try `TensorFlowV2Classifier` using `tensorflow.keras`, or make changes to the code of `KerasClassifier` to support the MSE loss function or wait for the upcoming releases of ART.

**Comment by khedher1984** [comment]
Thank you for your answer !
Have you any idea about the next release incluse the MSE function in Kerasclassifier ?

**Comment by beat-buesser** [comment]
@khedher1984 No, I don't think it is part of a release plan so far. Would you be interested to implement `MSE` in `KerasClassifier?` You could follow the example of the other loss functions and I could provide support.
