### ISSUE TITLE
Request for addition of Few Pixel Attack (One Pixel Attack)

### ISSUE THREAD

**Issue by shashankkotyan** [IBM/adversarial-robustness-toolbox#280]
I would like to add an implementation of Few Pixel Attack (https://arxiv.org/pdf/1906.06026.pdf) which is a generalisation of One Pixel Attack (https://arxiv.org/pdf/1710.08864.pdf).

**Comment by beat-buesser** [comment]
Hi @shashankkotyan Thank you for working on adding these new attacks to ART! Let us know any time if you have questions.
