### ISSUE TITLE
KerasClassifier does not check input shapes

### ISSUE THREAD

**Issue by seanpmorgan** [IBM/adversarial-robustness-toolbox#283]
Typically a Keras model will validate input shape before passing it through a model. Because of the way predictions are calculated in ART though this is not done:
https://github.com/IBM/adversarial-robustness-toolbox/blob/master/art/classifiers/keras.py#L215

On an architecture like [inception_resnet_v2](https://github.com/keras-team/keras-applications/blob/master/keras_applications/inception_resnet_v2.py#L239) this means that passing incorrect input shape will silently succeed, but should instead raise an error for user awareness and to make sure the correct weights are loaded. 

Minimal Example:
```
import numpy as np
from art.classifiers import KerasClassifier
from tensorflow.keras.applications.inception_resnet_v2 import InceptionResNetV2

if __name__ == "__main__":
    classifier = KerasClassifier(InceptionResNetV2(weights="imagenet"))
    print("Input Layer", classifier._model.layers[0].output_shape)
    img_batch = np.zeros((1, 224, 224, 3))

    # This will succeed
    print("Image shape", img_batch.shape)
    predictions = classifier.predict(img_batch)

    # This will fail as expected
    predictions = classifier._model.predict(img_batch)
```

**Comment by beat-buesser** [comment]
Hi @seanpmorgan Thank you for raising this issue! We will improve it in our next release 1.2.
