### ISSUE TITLE
Hard Code of Cuda Device in PyTorchClassifier

### ISSUE THREAD

**Issue by TreeLLi** [IBM/adversarial-robustness-toolbox#290]
**Describe the bug**
The default device is hard coded as `cuda:0` in the initialization of PyTorchClassifer class, which forces all GPU computation on the cuda:0 and hence disable the real parallelization on GPUs and also raises an error when such device is not available. 

The statement in `PyTorchClassifer` of `art.classifiers.pytorch`:  `self._device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")`. 

**System information (please complete the following information):**
 - Ubuntu
 - ART version: v1.1
 - PyTorch

**Comment by beat-buesser** [comment]
Hi @TreeLLi Thank you very much for using ART and raising this issue! We will fix it as soon as possible in our next release.

**Comment by TreeLLi** [comment]
Hi, thanks for your concern. I would like to suggest you to simply set the device as `cuda` instead of `cuda:0` so that users could control via the cuda default device, or adopt the same device as the underlying model's which may be more intuitive.

Apart from that, I personally recommend a chapter in your document clarifying your strategy on device and parallelisation.

**Comment by beat-buesser** [comment]
@TreeLLi Thank you very much for your recommendations. Would you be interested in making a pull request of your proposed solution?
