### ISSUE TITLE
Backdoor Poisoning Attacks

### ISSUE THREAD

**Issue by ebubae** [IBM/adversarial-robustness-toolbox#292]
**Is your feature request related to a problem? Please describe.**
Add backdoor poisoning examples to ART (see [Badnets, Gu 2017](https://arxiv.org/abs/1708.06733)). 

**Describe the solution you'd like**
Implementation of backdoor poisoning attacks as an extension of the `PoisoningAttack` class with notebook example and tests.

**Comment by beat-buesser** [comment]
Hi @ebubae Thank you very much for raising this feature request and working on implementing it! Would it be possible to add it to the ART v1.2.0 milestone?

**Comment by ebubae** [comment]
We can put this down for the v1.2.0 milestone.
