### ISSUE TITLE
RL model cannot apply this toolbox

### ISSUE THREAD

**Issue by QuXinghuaNTU** [IBM/adversarial-robustness-toolbox#313]
**Is your feature request related to a problem? Please describe.**
The ART can only accept the classifier trained by ART itself?

**Describe the solution you'd like**
When I try to apply the attack algorithm on the RL policy, I got the error below:
TypeError: For `FastGradientMethod` classifier must be an instance of `art.classifiers.classifier.Classifier`, the provided classifier is instance of (<class 'stable_baselines.common.base_class.OffPolicyRLModel'>,).

**Describe alternatives you've considered**
Does this mean that ART does not accept the model trained from outside?

**Additional context**

**Comment by beat-buesser** [comment]
Hi @QuXinghuaNTU Thank you for using ART!

ART does accept trained models as input to its classifiers. From the error message that you have shared above it looks like you are providing a model `class 'stable_baselines.common.base_class.OffPolicyRLModel'` directly to an attack `FastGradientMethod`. You have to first wrap your model inside an ART classifier (`art.classifiers.classifier.*`). The specific classifier type depends on your machine learning framework, e.g. `art.classifiers.classifier.PyTorchClassifier` for PyTorch, etc.

**Comment by QuXinghuaNTU** [comment]
I use the code below to transfer the RL model to ART model. It works.
`
your_RLmodel.load_weights("your_model.hdf5")
# this line change your model to ART model
classifier = KerasClassifier(model=your_RLmodel)`
