### ISSUE TITLE
cannot import name 'ClassifierNeuralNetwork'

### ISSUE THREAD

**Issue by Ninarehm** [IBM/adversarial-robustness-toolbox#322]
Hello,
I am getting the following error: cannot import name 'ClassifierNeuralNetwork'  using the following art version Adversarial-Robustness-Toolbox==1.0.0. I was wondering if you could help me.
Thanks.

**Comment by beat-buesser** [comment]
Hi @Ninarehm Thank you for using ART! Could you please provide more information on what you are trying to do e.g. a code snippet that leads to your observation?

**Comment by Ninarehm** [comment]
Hi. I am just trying to run the poisoning_attack_svm.ipynb and get the above error!

**Comment by Ninarehm** [comment]
<img width="750" alt="issue" src="https://user-images.githubusercontent.com/13911211/75919933-48621b00-5e13-11ea-98e4-d8ab3b6226e5.png">

**Comment by beat-buesser** [comment]
So far I'm not able to reproduce it with ART 1.0.0.

@Ninarehm Could you please confirm that your notebook is actually running with ART 1.0.0?

@ebubae Have you seen this error before with the poisoning SVM notebook?

**Comment by ebubae** [comment]
@beat-buesser I haven't run into this problem. I couldn't replicate this issue on the `master` or `dev_1.2.0` branch.

**Comment by Ninarehm** [comment]
I was able to make it work. Thanks. I’ll close the issue.
