### ISSUE TITLE
Unexpected Dtype Cast Caused By Clipping

### ISSUE THREAD

**Issue by TreeLLi** [IBM/adversarial-robustness-toolbox#366]
**Describe the bug**
The `dtype` of input tensor can be unintentionally converted to `np.float64`, default in numpy, from `np.float32`, specified explicitly in the config file, by the operation of clipping after enabling random initialization in the protocols such as PGD and FGM. This will later raise an dtype mismatch error between the input (float32) and the weights of model (float64).

The problem is that the tensor after clipped is applied a forced dtype cast to float32 in the code line **309** in the file `art\attacks\evasion\fast_gradient.py`. I suggest to apply such dtype cast after the clipping in order to fix it.

**To Reproduce**
1. explicitly pass a tuple of numpy ndarray, default dtype is np.float64, as clip ranges to the constructor of classifier wrapper class.
2. enable the random intialization by setting the parameter `num_random_init` greater than or equal to 1 when constructing specific attack class e.g. FGM
3. normally run the generate method to perturb the input

**Expected behavior**
the dtype of clip range should not change the dtype of input tensor during the perturbation process.

**System information (please complete the following information):**
 - Ubuntu 18.04
 - Python 3.6
 - ART latest version
 - PyTorch

**Comment by TreeLLi** [comment]
sorry that there is a typo in the description of bug. The mismatch of dtype should be the input (float64) and the weights of model (float32).

**Comment by beat-buesser** [comment]
Hi @TreeLLi Thank you for reporting this issue! We will investigate and fix it as soon as possible.

**Comment by TreeLLi** [comment]
Hi, thanks for your great work and concern of this issue. I am happy to give more detail if need.

**Comment by beat-buesser** [comment]
@TreeLLi I think a similar Dtype change can happen in line 295 if the clip_values are provided as np.float64. Have you observed similar problems with `num_random_init=0`?

I think we should add in both lines `.astype(ART_NUMPY_DTYPE)` after np.clip().

@TreeLLi Would you be interested to implement a solution and make a pull request? Otherwise I can I go ahead and make the changes.

**Comment by TreeLLi** [comment]
There is no problem with `num_random_init=0`, even though `_apply_perturbation` method with clipping may change the dtype of its return. In the case without random initialization, the dtype of `x_adv` variable in the method body is fixed as `np.float32` and the slicing assignment operation, line 323, in numpy seem to implicitly perform the dtype cast to the same one as the LHS variable's i.e. `np.float32`. However, I do agree with you to also care about the potential dtype conversion at the line 295, since it may raise an exception at another place.

I would like to suggest that we conver the dtype of `clip_values` to `ART_NUMPY_DTYPE` initially e.g. in the initializer of the class `Classifier` instead of doing conversion wherever np.clip called. I am happy to make a pull request for this issue.

**Comment by beat-buesser** [comment]
That's really great and I'm looking forward to the pull request! I think your solution is the best one and the explanation makes sense. We are currently working on branch `dev_1.3.0` for the upcoming release, this would be the target branch for this issue. Let us know anytime if you have questions.

**Comment by TreeLLi** [comment]
Hi, I have implemented a fix and tested in my program which performs FGM and PGD with `num_random_init=1`. The solution just works well as we expected. However, I noticed that unit tests are required in your contribution guideline, but I think it may be better to modify the existing FGM and PGD attack tests to cover the aforementioned situations instead of creating a new separate test. Please tell me how you think and if I need to do anything regarding the unit test.

**Comment by beat-buesser** [comment]
That's great news! I also think that these changes don't require new unittests. I would suggest that you go ahead with opening a pull request to target branch `dev_1.3.0` and then we can see its Travis CI results and reason which unittests might require updates.
