### ISSUE TITLE
Obfuscated/Vanishing Gradient Tests and Warning

### ISSUE THREAD

**Issue by keykholt** [IBM/adversarial-robustness-toolbox#368]
**Is your feature request related to a problem? Please describe.**
When performing certain adversarial attacks such as fast gradient descent, the attack can fail if the gradient returned is zero. This can be due to a number of factors such as a some non-differentiable layer, saturation, etc. The issue is that the attack will fail silently; It does not report that a zero gradient is present.

**Describe the solution you'd like**
It would be nice if when performing gradient dependent attacks a warning message would be presented to the user so they are aware the attack failed to find adversarial inputs due to an obfuscated or vanishing gradient rather than due to true adversarial robustness.

In addition, it would be useful if a test for obfuscated gradients could be added as an additional reporting metric for users to quickly check their models for such a property. This additional test could be reused when generating the warning message described above.

**Describe alternatives you've considered**
Currently, I manually check the gradient before performing the attack

**Comment by mathsinn** [comment]
I think that's a very good idea. We just saw, in #367, another example where vanishing gradients led to unexpected attack success rates.

**Comment by beat-buesser** [comment]
Hi @keykholt I think this is a great idea. Would you be interested to implement a solution?

**Comment by keykholt** [comment]
Sure thing.

**Comment by beat-buesser** [comment]
Great!
