### ISSUE TITLE
Improve logging for fit_generator on keras and pytorch

### ISSUE THREAD

**Issue by davidslater** [IBM/adversarial-robustness-toolbox#372]
**Is your feature request related to a problem? Please describe.**
When using a vanilla `DataGenerator` as input, `PyTorchClassifier.fit_generator` does not provide any logging, while `KerasClassifier.fit_generator` treats each batch as a single epoch, resulting in a ton of logging.

**Describe the solution you'd like**
Typical logging, one line per epoch, updating throughout that epoch. For the `KerasClassifier`, I think it works with a `KerasDataGenerator` as expected. Is it possible to get this functionality with the base `DataGenerator`?

**Comment by beat-buesser** [comment]
I think this could be related to the work in #87.

@ririnicolae I think you are working on #87 for ART 1.3. Will #87 solve this issue?

**Comment by davidslater** [comment]
I think that #87 will solve the issue, assuming the method used for `fit` is used for `fit_generator`.
