### ISSUE TITLE
Poisoning defense with not in-memory dataset

### ISSUE THREAD

**Issue by davidslater** [IBM/adversarial-robustness-toolbox#373]
**Is your feature request related to a problem? Please describe.**
Most (if not all) poisoning filtering defenses, such as `ActivationDefense`, require the entire dataset to be passed in, in-memory. This doesn't work for larger datasets or on memory-constrained systems for moderate sized datasets.

**Describe the solution you'd like**
The ability to pass in a `DataGenerator` instead of a full dataset.

**Comment by Nathalie-B** [comment]
Hi @davidslater we can look into this. How big is the dataset you are trying to fit in? We want to test with the settings you are working with. Thanks.

**Comment by davidslater** [comment]
Currently, we're just working with GTSRB, though we would like to expand this to larger datasets.
