### ISSUE TITLE
JSMA weird behavior

### ISSUE THREAD

**Issue by hussainkarafallah** [IBM/adversarial-robustness-toolbox#382]
I am using JSMA on my keras model
First weird thing is, if i call the generate function without providing y parameter (target labels) it runs normally (which is not expected)
Second thing is, even when i run it , it yields examples that don't change my model prediction (not a single successful one of them). I had to put theta >= 400 in order to be able to generate examples that my model misses. Given that my features have 0 mean and 1 std.
I am using a keras model.
I have tried FGSM and deepfool and both of them were fine, but JSMA isn't working at all.

**Comment by beat-buesser** [comment]
Hi @hussainkarafallah Thank you for using ART! Could you please share a python script or notebook which reproduces your observations?

**Comment by tagomaru** [comment]
Hi @hussainkarafallah 

> First weird thing is, if i call the generate function without providing y parameter (target labels) it runs normally (which is not expected)

I think this is an expected behavior according to [here](https://github.com/IBM/adversarial-robustness-toolbox/blob/master/art/attacks/evasion/saliency_map.py#L87-L92)

```python
        # Determine target classes for attack
        if y is None:
            # Randomly choose target from the incorrect classes for each sample
            from art.utils import random_targets

            targets = np.argmax(random_targets(preds, self.classifier.nb_classes()), axis=1)
```

If you do not pass `y`, it generates randomly target.

>Second thing is, even when i run it , it yields examples that don't change my model prediction (not a single successful one of them). I had to put theta >= 400 in order to be able to generate examples that my model misses. Given that my features have 0 mean and 1 std.

Is your image scale from 0 to 255.0?
