### ISSUE TITLE
attack_decision_based_boundary.ipynb seems not to consider preprocessing regarding ImageNet correctly.

### ISSUE THREAD

**Issue by tagomaru** [IBM/adversarial-robustness-toolbox#395]
**[attack_decision_based_boundary.ipynb](https://github.com/IBM/adversarial-robustness-toolbox/blob/master/notebooks/attack_decision_based_boundary.ipynb) seems not to consider preprocessing regarding ImageNet correctly.**

The below code seems to consider imagenet BGR-mean correctly.

```python
mean_imagenet = np.zeros([224, 224, 3])
mean_imagenet[...,0].fill(103.939)
mean_imagenet[...,1].fill(116.779)
mean_imagenet[...,2].fill(123.68)
model = ResNet50(weights='imagenet')
classifier = KerasClassifier(clip_values=(0, 255), model=model, preprocessing=(mean_imagenet, 1))
```

On the other hand, the part below seems not to consider BGR correctly.
I think `target_image` and `x_adv` may need to be changed to the value of not RGB but BGR and `x_adv[0]` should be passed to `plt.imshow` after changing it the value of RGB.

```python
    x_adv = attack.generate(x=np.array([target_image]), y=to_categorical([866], 1000), x_adv_init=x_adv)

    #clear_output()    
    print("Adversarial image at step %d." % (i * iter_step), "L2 error", 
          np.linalg.norm(np.reshape(x_adv[0] - target_image, [-1])),
          "and class label %d." % np.argmax(classifier.predict(x_adv)[0]))
    plt.imshow(x_adv[0].astype(np.uint))
    plt.show(block=False)
```

For example, the below project changes RGB to BGR.

[attack_defence_imagenet.ipynb](https://github.com/IBM/adversarial-robustness-toolbox/blob/master/notebooks/attack_defence_imagenet.ipynb)
```python
# Same as for the original model, we expand the dimension of the inputs.
# We also swap the color channels (RGB -> BGR):
x_art = np.expand_dims(images[idx], axis=0)[..., ::-1] 
```

Is my understanding correct?

**Comment by beat-buesser** [comment]
Hi @tagomaru Thank you very much for raising this issue and providing a detailed description!

@minhitbk What do you think?

**Comment by minhitbk** [comment]
@tagomaru Thank you very much for raising the issue. We will fix it soon.

**Comment by tagomaru** [comment]
HI @minhitbk  and @beat-buesser 

Thank you for your answer.
If you can share the two original files (koala.jpg and truck.jpg) with me, I will fix it for you.

**Comment by beat-buesser** [comment]
@tagomaru Thank you, that would be great! The two original images are from the library `imagenet_stubs` which gets installed from GitHub in the first cell of the notebook.

**Comment by tagomaru** [comment]
@beat-buesser Thank you! 
I will do.
