### ISSUE TITLE
Spectral Signature Backdoor Poisoning Defense

### ISSUE THREAD

**Issue by ng390** [IBM/adversarial-robustness-toolbox#396]
**Is your feature request related to a problem? Please describe.**
Add defense from [Spectral Signatures in Backdoor Attacks](https://papers.nips.cc/paper/8024-spectral-signatures-in-backdoor-attacks.pdf)

**Describe the solution you'd like**
Implementation of the spectral signature defense as a poison filtering defense for neural networks. Should include basic unit tests and necessary documentation.

**Comment by beat-buesser** [comment]
Hi @ng390 Thank you for using ART and raising this feature request! Would you be interested in implementing this defence for ART?

@ebubae What do you think?

**Comment by ebubae** [comment]
Hey @beat-buesser, @ng390 has reached out to me and I'm helping him standardizing his implementation within ART. Thanks again @ng390 for your contribution. I'll be looking forward to reviewing this PR.
