### ISSUE TITLE
error running the examples

### ISSUE THREAD

**Issue by cenyuzhang** [IBM/adversarial-robustness-toolbox#4]
Hi, I encountered the following error when running the examples:

Traceback (most recent call last):
  File "examples/mnist_cnn_fgsm.py", line 11, in <module>
    from config import config_dict
  File "/anaconda3/lib/python3.6/site-packages/config/__init__.py", line 47, in <module>
    with open(config_file, mode='rt') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/anaconda3/lib/python3.6/site-packages/config/config.ini'

**Comment by ririnicolae** [comment]
Thanks for letting us know! How did you install ART (download + install or from PyPi)?

**Comment by cenyuzhang** [comment]
@ririnicolae thanks for the quick response! I installed and use Anaconda3.

**Comment by ririnicolae** [comment]
I will fix this for future installs. Meanwhile, the quick fix for you would be to manually add `config.ini` in `/anaconda3/lib/python3.6/site-packages/config` with the following content:
```
[DEFAULT]
profile=LOCAL

[LOCAL]
data_path=~/.data
mnist_path=~/.data/mnist
cifar10_path=~/.data/cifar-10
stl10_path=~/.data/stl-10
imagenet_path=~/.data/imagenet
```

**Comment by cenyuzhang** [comment]
@ririnicolae thanks!
