### ISSUE TITLE
Allow pip to install ART with the full set of required and optional dependencies

### ISSUE THREAD

**Issue by hesseltuinhof** [IBM/adversarial-robustness-toolbox#405]
Currently, dependencies that are only used in a small subset of methods are often not included in the requirements list. However, this could potentially throw errors for users when those are unaware of the fact that ART expects such dependencies to be maintained by the user itself. E.g. randomized smoothing requires the `statsmodels` dependency in order to use `RandomizedSmoothing.certify(*args, **kwargs)`. 

We could add an additional key to the `setup.py` that allows a user to install combinations like
* ART + all dependencies
* ART + tensorflow

This can be achieved with the following:
```python
setup(
    extras_require={
        'extra': ['statsmodels', 'pydub', ...],
        'tensorflow': ['tensorflow']
    }
```
This allows one to install ART with the additional dependencies and Tensorflow via `pip install adversarial-robustness-toolbox[extra,tensorflow]`.

Looking forwarding to hearing some opinions :rocket:

**Comment by beat-buesser** [comment]
I think if we do it once we could provide options for all frameworks, e.g.:
- keras
- pytorch
- keras
- scikit-learn
- xgboost
- lightgbm
- catboost

and the general options:
- all (install everything)

I'm wondering if we should keep the current selection of the most used dependencies excluding the framework as default.

**Comment by hesseltuinhof** [comment]
I think that one might even consider merging the **base** and **extra** packages as default. The extra dependencies are a small set at the moment and small in size. So this should not create too much installation overhead.

* Framework dependencies (individual option)
  * `catboost`
  * `GPy`
  * `keras`, `h5py`
  * `lightgbm`
  * `mxnet`
  * `tensorflow`, `tensorflow-addons`, `h5py`
  * `torch`, `torchvision`
  * `xgboost`
* Base dependecies
  * `matplotlib`
  * `numpy`
  * `scipy`
  * `six`
  * `sklearn` (used accross ART multiple times, e.g. (poison) detection and poison attack)
* Extra dependencies
  * `cma`
  * `pillow`
  * `pydub`
  * `resampy`
  * `statsmodels`
* Test dependencies (not listed here)

As we were discussing this earlier @minhitbk I would also very much appreciate your opinion :+1:
