### ISSUE TITLE
Adversarial Trainer progress bar

### ISSUE THREAD

**Issue by hussainkarafallah** [IBM/adversarial-robustness-toolbox#418]
When initiating an adversarial trainer defence and fitting a training set, the progress bar is malfunctioning, it shows something like
`Epoch 1/1
1/1 [==============================] - 0s 243ms/step - loss: 0.5083 - accuracy: 0.8477
Epoch 1/1
1/1 [==============================] - 0s 247ms/step - loss: 0.5404 - accuracy: 0.8281
Epoch 1/1
1/1 [==============================] - 0s 249ms/step - loss: 0.4848 - accuracy: 0.8594
Epoch 1/1
1/1 [==============================] - 0s 243ms/step - loss: 0.3498 - accuracy: 0.9023`

which from what I can see is one line per each mini-batch

**Comment by beat-buesser** [comment]
Hi @hussainkarafallah Thank you for using ART and raising this issue! We will take a look as soon as possible.
Would you be interested to investigate a possible solution?
