### ISSUE TITLE
Thermometer encoding usage

### ISSUE THREAD

**Issue by maliwin** [IBM/adversarial-robustness-toolbox#450]
Hi, I'm attempting to use the thermometer encoding preprocessing defence, but I'm confused about the usage procedure of it and I didn't see an example/notebook with that particular defence.

Here's a minimal example:
```python
import numpy as np
from PIL import Image
from tensorflow.keras.applications.xception import Xception
from art.classifiers import TensorFlowV2Classifier
from art.defences.preprocessor import ThermometerEncoding

target_image = Image.open('dragonfly.jpg')
target_image = target_image.resize((299, 299), resample=Image.LANCZOS)
target_image = np.array(target_image, dtype=np.float64)

model = Xception(weights='imagenet')
target_image = target_image / 255
defence = ThermometerEncoding(clip_values=(0, 1))
art_model = TensorFlowV2Classifier(model=model, nb_classes=1000, input_shape=(299, 299, 3), clip_values=(0, 1),
                                   preprocessing=(0.5, 0.5), preprocessing_defences=defence)
art_model.predict(np.array([target_image]))
```

Any image will do in place of `dragonfly.jpg`, so I'm not attaching it here.
I would expect to still be able to use the wrapped model normally, i.e. like this `art_model.predict(np.array([target_image]))` but instead I get the following traceback:

```
WARNING:tensorflow:Model was constructed with shape (None, 299, 299, 3) for input Tensor("input_1:0", shape=(None, 299, 299, 3), dtype=float32), but it was called on an input with incompatible shape (1, 299, 299, 30).
Traceback (most recent call last):
  File "...\Python\Python38\lib\contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "...\Python\Python38\lib\site-packages\tensorflow\python\keras\engine\base_layer_utils.py", line 443, in enter
    yield
  File "...\Python\Python38\lib\site-packages\tensorflow\python\keras\engine\base_layer.py", line 968, in __call__
    outputs = self.call(cast_inputs, *args, **kwargs)
  File "...\Python\Python38\lib\site-packages\tensorflow\python\keras\engine\network.py", line 717, in call
    return self._run_internal_graph(
  File "...\Python\Python38\lib\site-packages\tensorflow\python\keras\engine\network.py", line 888, in _run_internal_graph
    output_tensors = layer(computed_tensors, **kwargs)
  File "...\Python\Python38\lib\site-packages\tensorflow\python\keras\engine\base_layer.py", line 968, in __call__
    outputs = self.call(cast_inputs, *args, **kwargs)
  File "...\Python\Python38\lib\site-packages\tensorflow\python\keras\layers\convolutional.py", line 195, in call
    self._convolution_op = nn_ops.Convolution(
  File "...\Python\Python38\lib\site-packages\tensorflow\python\ops\nn_ops.py", line 1060, in __init__
    raise ValueError(
ValueError: number of input channels does not match corresponding dimension of filter, 30 != 3
```

*   OS Windows 10
*   Python version 3.8.1
*   ART version dev_1.3.0
*   TensorFlow 2.2.0

Please note that I am using the dev version currently, which I switched to due to #436, but I have also tested it with 1.2.0 and get the same output.

**Comment by maliwin** [comment]
Oh, after taking a closer look, I assume the model has to have an input channel of channels * num_space, i.e. (299, 299, 3 * 10), where `num_space` is the parameter in the thermometer encoder. Is this correct?

**Comment by beat-buesser** [comment]
@maliwin Thank you for raising this question! Yes, `ThermometerEncoding` is a defence that has to be applied during `fit` and `predict`, which means you have to first train your model on encoded data because the encoding changes the image shape (https://openreview.net/pdf?id=S18Su--CW, section 3).

**Comment by maliwin** [comment]
Thank you again @beat-buesser for such a quick response. I guess I should've paid more attention to what the defence actually did before opening up an issue, sorry! 😅 

Consider the question answered.

**Comment by beat-buesser** [comment]
@maliwin No worries! Please open a new issue whenever you think there is something strange with ART, we are very interested to learn about it. For this issue for example we see that we should add a better error message that explains that the provided model is not compatible with the defence. I made a note to fix this.

**Comment by mathsinn** [comment]
Hi @maliwin , we have identified and fixed two bugs in the thermometer encoding, please check out PR #467. Using the fix with the example that you provided seems to work - could you also try please?

**Comment by maliwin** [comment]
Hi @mathsinn, thank you for providing a fix this quickly. I currently have 3 models trained without the fix (for different epochs). I took a look at the fix and it seems like those models will not be compatible with the new version anymore.

I will train 3 new models and compare them to the 3 old ones, and I will see if it fixes the original problem of using thermometer encoding with FGSM/PGD attacks.

**Comment by maliwin** [comment]
@mathsinn It does seem to work now with both FGSM and PGD.
