### ISSUE TITLE
wildcard in loss_gradient function

### ISSUE THREAD

**Issue by hrosenberg** [IBM/adversarial-robustness-toolbox#457]
When running the loss_gradient function, IBM ART Keras classifiers do not handle wildcards when specifying input dimension.  This bug is a showstopper for us.  Please advise on a solution.   See relevant portion of stack trace below.  Thanks!

```
File "/opt/conda/lib/python3.7/site-packages/art/classifiers/keras.py", line 275, in loss_gradient
    self._input_shape, x.shape[1:]
ValueError: Error when checking x: expected x to have shape (512, None, 1) but got array with shape (512, 200, 1)
```

OS: Ubuntu 18.04 LTS
Python Version: 3.7 (in a docker container)
ART version: current stable version
Keras/tensorflow 2: current stable version

**Comment by mathsinn** [comment]
Hi @hrosenberg , we're working on it: https://github.com/IBM/adversarial-robustness-toolbox/pull/458

In the interim, it will be helpful if you can provide a minimum example that would allow us to test the functionality that you're seeking for. Thanks!
