### ISSUE TITLE
Failed import in  art.attacks.evasion.__init__.py

### ISSUE THREAD

**Issue by nmegiddo** [IBM/adversarial-robustness-toolbox#477]
The file   art.attacks.evasion.__init__.py   has the following import request:

from art.attacks.evasion.adversarial_patch.adversarial_patch import (
    AdversarialPatch,
    AdversarialPatchNumpy,
    AdversarialPatchTensorFlowV2,
)

However, it seems that the structure of   art.attacks.evasion.adversarial_patch has changed,
and this import cannot be fulfilled.

**Comment by beat-buesser** [comment]
Hi @nmegiddo Thank you very much for raising this issue! The imports above are form ART 1.3. Which version of ART have you installed?

**Comment by nmegiddo** [comment]
Hi Beat,The import appears in the current file:https://github.com/IBM/adversarial-robustness-toolbox/blob/master/art/attacks/evasion/__init__.py

I believe it is ART 1.3
    On Monday, June 22, 2020, 03:41:20 AM PDT, Beat Buesser <notifications@github.com> wrote:  
 
 


Hi @nmegiddo Thank you very much for raising this issue! The imports above are form ART 1.3. Which version of ART have you installed?

**Comment by beat-buesser** [comment]
I think you are right. It currently works because we are re-importing the classes that another class has imported and are not actually directly importing the class we want to import. I agree, we should make the import paths explicit for `AdversarialPatch` and also for `ProjectedGradientDescent`.
