### ISSUE TITLE
bug in "to_categorical" implementation

### ISSUE THREAD

**Issue by zivka-bgu** [IBM/adversarial-robustness-toolbox#7]
Hi,

There is a bug in the "to_categorical" utility function making it construct an array totally filled with "1".
This in turn prevents the classifier loss from dropping etc...
(discovered that when playing with the CIFAR example)

I have replaced - _categorical[np.arange(labels.shape[0]), labels] = 1_
with - 
_    for i in range(labels.shape[0]):
        categorical[i][labels[i]] = 1_

which solved the problem
Ziv.

**Comment by ririnicolae** [comment]
Hi, Ziv! Could you please provide a test case that triggers this bug? 
The following test case works:
```from art.utils import to_categorical
import numpy as np
labels = np.random.randint(10, size=9)
print(to_categorical(labels, nb_classes=10))
```

**Comment by zivka-bgu** [comment]
Hi,

I was running your own CIFAR10 example. The Y values matrices were set to all ones, which prevented model training and evaluation

When I changed the line mentioned in the original post everything started working as expected

Ziv

**Comment by ririnicolae** [comment]
Ok, I reproduced it on my side. Will get back to you with a fix!

**Comment by zivka-bgu** [comment]
Thanks!

Glad I was able to help
Ziv
