### ISSUE TITLE
Adversarial Patch size problem

### ISSUE THREAD

**Issue by WladimirDelaCadena** [IBM/adversarial-robustness-toolbox#77]
By running 
`adv_patch = AdversarialPatch(classifier,patch_shape=(32, 32, 3), max_iter = 100)`
it turns out that patch_shape must have the same dimension as the input image. But in theory a patch could be smaller. Going into the source code the problem is by summing the image with the patch that is not done properly

**Comment by ririnicolae** [comment]
@WladimirDelaCadena Thanks for identifying this issue, we'll look into it.

**Comment by ririnicolae** [comment]
@WladimirDelaCadena Have you taken a look at our example for adversarial patch generation? https://github.com/IBM/adversarial-robustness-toolbox/blob/master/notebooks/adversarial_patch.ipynb The patch is indeed generated to the original input size of the classifier, but then you can apply it to any image with different scales. The attack has the method `apply_patch` for that. Let me know if the example helps.

**Comment by WladimirDelaCadena** [comment]
@ririnicolae Thanks, yes indeed the apply_patch function scales the patch. I misunderstood the functionality respect to the paper. Then, maybe the patch_shape parameter is not needed. Since it must have certain dimensions, they can be taken from the input data properties

**Comment by ririnicolae** [comment]
@WladimirDelaCadena Thanks for the suggestion, I believe you are right. We'll update the code to reflect this.
