### ISSUE TITLE
adversarial-training-mnist.ipynb does not able to read the mnist_cnn_original.h5

### ISSUE THREAD

**Issue by jinglin80** [IBM/adversarial-robustness-toolbox#88]
Using Jupyter notebook to run adversarial-training-mnist.ipynb, the model mnist_cnn_original.h5 (in models) folder cannot open. Strangely, the mnist_cnn_original.h5 has only 132 bytes. This is not likely the size of a model file.

**Comment by ririnicolae** [comment]
@jinglin80 Thanks for reporting this issue. It is related to #63 and we're working on solving it. Meanwhile, a quick fix for you would be to get the model from an older version where the model is not corrupted (say, 0.6.0).

**Comment by jinglin80** [comment]
Thank you for the quick reply. Though the model is ok now, KerasClassifier is reporting the following error. 

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-3-ef6fe94c52ed> in <module>
      1 classifier_model = load_model("../models/mnist_cnn_original.h5")
----> 2 classifier = KerasClassifier((min_, max_), classifier_model, use_logits=False)

TypeError: __init__() got multiple values for argument 'use_logits'

**Comment by ririnicolae** [comment]
@jinglin80 Could you try to change the faulty line to the following:
```
classifier = KerasClassifier(clip_values=(min_, max_), model=classifier_model, use_logits=False)
```
and let me know if it's fixed?

**Comment by jinglin80** [comment]
Yes, it is fixed. Thank you!
